/*
 FireShot - Webpage Screenshots and Annotations
 Copyright (C) 2007-2019 Evgeny Suslikov (evgeny@suslikov.ru)
*/
var scriptLoaded=!0,stubbornNodes=[],modifiedNodes2=[],divsSnapshot=[],commPortName,options,sbStyle,lockedScrollEvent,hiddenAttributeFlagName="__fireshotHiddenElement",initialAttributeFlagName="__fireshotInitialElement";chrome.runtime.sendMessage&&chrome.runtime.sendMessage({message:"getPortName"},function(a){commPortName=a.portName;getConsolePtr()("Obtained port name: "+commPortName)});function getOptionFromScript(a,d){return options[a]||d}
function enableSomeElements(a){"undefined"===typeof a&&(a=!0);var d;if(window.location.href.match(/https?:\/\/mail\.google\.com/i)){for(var h=document.createNodeIterator(document.body,NodeFilter.SHOW_ELEMENT,null,!1),e;e=h.nextNode();)"TD"==e.nodeName&&e.getAttribute("class")&&e.getAttribute("class").match(/Bu y3/i)&&e.style.setProperty("display",a?"":"none","important");(d=document.getElementById(":ro"))&&d.style.setProperty("display",a?"":"none","important");(d=document.getElementById(":5"))&&d.style.setProperty("display",
a?"":"none","important")}}
function hideObtrusiveElements(a,d){for(var h=[],e=a.getBoundingClientRect(),q=window.innerWidth*window.innerHeight+1,k=e.width*e.height+1,f=document.createNodeIterator(document.body,NodeFilter.SHOW_ELEMENT,null,!1),n=a!==getScrollingElement(),g;null!==(g=f.nextNode());)if("1"!==g.getAttribute(hiddenAttributeFlagName)){var l=g.getBoundingClientRect();if(!(g.scrollWidth>.9*window.innerWidth&&g.scrollHeight>.9*window.innerHeight&&g.clientWidth>.33*e.width&&g.clientHeight>.33*e.height||0===l.width*l.height||
.35<l.width*l.height/q)){h.push({div:g,x:l.left,y:l.top});for(var p=0;p<divsSnapshot.length;++p)if(divsSnapshot[p].div===g){if((!d&&divsSnapshot[p].y===l.top||d&&divsSnapshot[p].x===l.left)&&!elementInHiddenList(g)){if(g===a||n&&isChildOf(g,a))continue;if(n&&isChildOf(a,g)&&.35<l.width*l.height/k)continue;a:{for(l=g;l&&l!=document;){p=document.defaultView.getComputedStyle(l,"");if("hidden"===p.visibility||"none"===p.display||"0"===p.opacity){l=!0;break a}l=l.parentNode}l=!1}l?g.setAttribute(hiddenAttributeFlagName,
"1"):hideElement(g)}break}}}divsSnapshot=h}function elementInHiddenList(a){for(var d=0;d<stubbornNodes.length;++d)if(stubbornNodes[d].elem===a)return!0;return!1}
function hideElement(a){getConsolePtr()("Hiding:");getConsolePtr()(a);stubbornNodes.push({elem:a,opacity:a.style.getPropertyValue("opacity"),animation:a.style.getPropertyValue("animation"),transitionDuration:a.style.getPropertyValue("transition-duration")});a.style.setProperty("opacity","0");a.style.setProperty("animation","unset");a.style.setProperty("transition-duration","0s");a.setAttribute(hiddenAttributeFlagName,"1")}
function hideStubbornElements(a,d){var h=a?a.getBoundingClientRect():void 0,e=h?h.width:window.innerWidth;h=h?h.height:window.innerHeight;d=d||!1;for(var q=document.createNodeIterator(document.body,NodeFilter.SHOW_ELEMENT,null,!1),k;k=q.nextNode();){var f=document.defaultView.getComputedStyle(k,"");!f||"fixed"!=f.getPropertyValue("position")&&"sticky"!=f.getPropertyValue("position")||elementInHiddenList(k)||"none"==f.getPropertyValue("display")||a&&isChildOf(k,a)||d&&k.scrollWidth>window.innerWidth||
k.scrollWidth>.9*window.innerWidth&&k.scrollHeight>.9*window.innerHeight&&k.clientWidth>.33*e&&k.clientHeight>.33*h||(getConsolePtr()("Found stubborn element "+k.id),hideElement(k))}for(a=0;a<stubbornNodes.length;++a)stubbornNodes[a].elem.style.setProperty("opacity","0")}
function showHiddenElements(){for(var a=0;a<stubbornNodes.length;++a)stubbornNodes[a].elem.style.setProperty("opacity",stubbornNodes[a].opacity),stubbornNodes[a].elem.style.setProperty("animation",stubbornNodes[a].animation),stubbornNodes[a].elem.style.setProperty("transition-duration",stubbornNodes[a].transitionDuration)}
function removeCustomAttributes(){for(var a=document.createNodeIterator(document.body,NodeFilter.SHOW_ELEMENT,null,!1),d;d=a.nextNode();)d.removeAttribute(hiddenAttributeFlagName),d.removeAttribute(initialAttributeFlagName)}function createInitialElementsSnapshot(){for(var a=document.createNodeIterator(document.body,NodeFilter.SHOW_ELEMENT,null,!1),d;d=a.nextNode();)d.setAttribute(hiddenAttributeFlagName,"1")}
function hideNewElements(){for(var a=document.createNodeIterator(document.body,NodeFilter.SHOW_ELEMENT,null,!1),d;d=a.nextNode();)"1"!==d.getAttribute(hiddenAttributeFlagName)&&hideElement(d)}
function FBAdapter(){var a=[];(function(){a=Array.prototype.slice.call(document.querySelectorAll("DIV")).map(function(a){return{element:a,top:a.style.top}}).filter(function(a){return"absolute"==a.element.style.position})})();return{undoSwitchingToFixedPositions:function(){a.forEach(function(a){"fixed"==a.element.style.position&&(a.element.style.position="absolute",a.element.style.top=a.top)})}}}
function getAltExtents(){var a=window.document,d=a.documentElement;d=d.clientWidth?d.clientWidth:window.innerWidth;var h=-1;0>h&&(h=window.innerHeight-getSBHeight(window));if(a.body){var e="CSS1Compat"==a.compatMode?a.documentElement.scrollWidth:a.body.scrollWidth,q=a.documentElement.scrollHeight,k="CSS1Compat"==a.compatMode?a.documentElement.clientWidth:a.body.clientWidth;a="CSS1Compat"==a.compatMode?a.documentElement.clientHeight:a.body.clientHeight;e<k&&(e=k);q<a&&(q=a);d<e&&(d=e);h<q&&(h=q)}return{Width:d,
Height:h}}
function findScrolledElement(a,d){for(var h=document,e,q=location.href,k=document.createNodeIterator(document.body,NodeFilter.SHOW_ELEMENT,null,!1),f;null!==(f=k.nextNode());)if(0<f.scrollWidth&&0<f.scrollHeight&&(f.scrollWidth>f.clientWidth||f.scrollHeight>f.clientHeight)&&(q.match(/https?:\/\/www\.(facebook|fb)\.com/i)&&f.scrollHeight>.5*d||f.scrollWidth>a&&f.scrollHeight>.5*d||f.scrollHeight>d&&f.scrollWidth>.3*a||f.clientWidth>.7*a&&f.clientHeight>.7*d)){var n=h.defaultView.getComputedStyle(f,"");
isScrollableStyle(n)&&(!e||e.scrollWidth*e.scrollHeight<f.scrollWidth*f.scrollHeight)&&(n=getElementExtents(f),n.absoluteX+n.w<=window.innerWidth+2&&n.absoluteY+n.h<=window.innerHeight+2&&(!e||e.scrollWidth*e.scrollHeight<f.scrollWidth*f.scrollHeight)&&(e=f))}e&&(getConsolePtr()("Found scrolled element:"),getConsolePtr()(e));return e}
function getElementExtents(a){var d=a.getClientRects(),h={absoluteX:0,absoluteY:0,x:0,y:0,w:0,h:0};0<d.length&&(h.absoluteX=a.clientLeft+d[0].left,h.absoluteY=a.clientTop+d[0].top,h.w=d[0].width,h.h=d[0].height);return h}
function disableFloatingInView(a){var d=document,h=getElementExtents(a),e=window.innerWidth*window.innerHeight+1;modifiedNodes2=[];for(var q=d.createNodeIterator(d.documentElement,NodeFilter.SHOW_ELEMENT,null,!1),k;null!==(k=q.nextNode());){var f=d.defaultView.getComputedStyle(k,"");if(f&&"0"!==f.getPropertyValue("opacity")&&("absolute"==f.getPropertyValue("position")||"relative"==f.getPropertyValue("position"))){var n=getElementExtents(k);0===n.w*n.h||.35<n.w*n.h/e||k==a||!getIntersection(h.absoluteX,
h.absoluteY,h.w,h.h,n.absoluteX,n.absoluteY,n.w,n.h)||isChildOf(a,k)||isChildOf(k,a)||(getConsolePtr()("Hiding:"),getConsolePtr()(k),modifiedNodes2.push({object:k,opacity:f.getPropertyValue("opacity")}),k.style.setProperty("opacity","0","important"))}}}function disableScrollEvent(){lockedScrollEvent=function(a){a.stopImmediatePropagation()};window.addEventListener("scroll",lockedScrollEvent,!0)}function enableScrollEvent(){window.removeEventListener("scroll",lockedScrollEvent,!0)}
function enableFloatingInView(){for(var a=0;a<this.modifiedNodes2.length;a++)modifiedNodes2[a].object.style.setProperty("opacity",modifiedNodes2[a].opacity)}function getOffsets(a,d,h){var e={x:0,y:0};d===cModeVisible?(e.x=getScrollingElement().scrollLeft,e.y=getScrollingElement().scrollTop):d===cModeSelected?(e.x=h.left,e.y=h.top):a.div&&(e.x=a.left,e.y=a.top);return e}function getScrollingElement(){return document.scrollingElement||document.body}
chrome.runtime.onConnect.addListener(function(a){function d(b,c){options[b]=c;a.postMessage({topic:"setOption",optionName:b,optionValue:c})}function h(a,d){m=d;g=a;c=getScrollingElement();g!=cModeEntire||m||q||(m=findScrolledElement(c.scrollWidth,c.scrollHeight));u=m||C.body;m&&(c=m,m.scrollIntoView(),disableFloatingInView(m),N=m.style.zIndex,m.style.zIndex=2147483647);O=c.scrollTop;P=c.scrollLeft;v=c.scrollWidth;x=c.scrollHeight;B=D=E=void 0;if(!m){"hidden"===document.defaultView.getComputedStyle(document.body,
"").overflowX&&(B=u.style.overflowX,a=c.scrollHeight,u.style.overflowX="visible",a>=c.scrollHeight&&(u.style.overflowX=B,B=void 0));v=Math.max(C.documentElement.scrollWidth,u.scrollWidth,document.documentElement.clientWidth,u.offsetWidth,document.documentElement.offsetWidth);x=Math.max(C.documentElement.scrollHeight,u.scrollHeight,document.documentElement.clientHeight,u.offsetHeight,document.documentElement.offsetHeight);if(0>=v||0>=x)a=getAltExtents(),v=a.Width,x=a.Height;0>=v&&(v=1024);0>=x&&(x=
768)}g===cModeEntire&&(k?(c.scrollTop=1,c.scrollLeft=1,setTimeout(function(){c.scrollTop=0;c.scrollLeft=0},10)):(c.scrollTop=0,c.scrollLeft=0));J&&(Q=FBAdapter());g!==cModeVisible&&g!==cModeBrowser&&enableSomeElements(!1);m?(z=m.clientWidth,A=m.clientHeight):(z=window.innerWidth,A=window.innerHeight,v<window.innerWidth&&(v=window.innerWidth))}if(chrome.runtime.sendMessage&&a.name!=commPortName)getConsolePtr()("Comm port name is wrong: "+a.name+" <> "+commPortName);else{var e=!0,q=!1,k=0===window.navigator.plugins.length&&
isConsoleOpened(),f=1,n=1,g=0,l=0,p=1,w=1,K=!0,F=!0,z=0,A=0,G=0,L=0,R=0,S=0,t={left:0,top:0,right:0,bottom:0},m,C,u,c,O,P,T,U,V,B,E,D,W,v,x,N,X,y,H,J=window.location.href.match(/https?:\/\/www\.(facebook|fb)\.com/i),Q;stubbornNodes=[];modifiedNodes2=[];divsSnapshot=[];a.onMessage.addListener(function(b){switch(b.topic){case "init":X=b.p;H=b.native;window.isDebug|=b.debug;l=X?150:200;C=window.document;options=JSON.parse(b.options);q=b.frameMode;try{h(b.mode)}catch(Y){getConsolePtr()(Y.toString());
a.postMessage({topic:"initAborted"});return}W=document.documentElement.style.scrollBehavior;document.documentElement.style.scrollBehavior="initial";disableScrollEvent();if(g!==cModeSelected&&!m||k)T=!0,U=c.style.overflow,V=c.style.height,c.style.overflow="hidden",c.style.height=x+"px",document.scrollingElement||(D=document.defaultView.getComputedStyle(document.documentElement,"").overflowY,document.documentElement.style.overflowY="initial",E=document.defaultView.getComputedStyle(document.documentElement,
"").overflowX,document.documentElement.style.overflowX="initial");var u={topic:"initDone",url:document.location.toString(),title:document.title,cw:q&&frameElement?frames.parent.innerWidth:window.innerWidth,ch:q&&frameElement?frames.parent.innerHeight:window.innerHeight,emulation:k};J&&g===cModeEntire?setTimeout(function(){c.scrollTop=x;setTimeout(function(){c.scrollTop=0;setTimeout(function(){a.postMessage(u)},l)},l)},l):setTimeout(function(){a.postMessage(u)},l);break;case "setRatio":p=b.ratioW;
w=b.ratioH;getConsolePtr()("Ratios: "+p+", "+w);break;case "selectArea":if(!document.body){alert("Apologies, this page does not support capturing selections.");a.postMessage({topic:"areaSelectionCanceled"});enableScrollEvent();break}hideStubbornElements();var M=FireShotAddon.FSSelectionHint(document);H&&"false"!==getOptionFromScript(cShowSelectionHintPref,"true")&&M.show();FireShotAddon.FSSelector({browser:"chrome",extendedMode:H,doc:document}).makeSelection(function(b){H&&(M.isShown()?M.hide():d(cShowSelectionHintPref,
"false"));b.left==b.right||b.top==b.bottom?(a.postMessage({topic:"areaSelectionCanceled"}),showHiddenElements(),removeCustomAttributes(),enableScrollEvent()):(b.isScrollable?(getConsolePtr()("Capturing element:"),getConsolePtr()(b.selectedElement),h(cModeEntire,b.selectedElement)):(c.scrollLeft=b.left,c.scrollTop=b.top,G=c.scrollLeft,L=c.scrollTop,t.left=b.left,t.top=b.top,t.right=b.right,t.bottom=b.bottom),setTimeout(function(){hideStubbornElements();a.postMessage({topic:"areaSelected"})},l))});
break;case "scrollNext":if(e){y=new LinksGrabber(m||document);y.clearAttributes();y.markHiddenLinks();y.createLinksSnapshot();hideObtrusiveElements(c,!1);0===c.scrollLeft&&0===c.scrollTop&&y.checkClickableLinks();e=!1;setTimeout(function(){a.postMessage({topic:"scrollDone",x:c.scrollLeft*p,y:c.scrollTop*w})},l);return}if(K&&g!=cModeVisible&&g!=cModeBrowser){var Z=g==cModeSelected?t.right:v;var I=Math.max(z-30,0);var r=c.scrollLeft;c.scrollLeft+=Math.max(0,Math.min(I,Z-(c.scrollLeft+I)+20));if(K=c.scrollLeft!=
r&&c.scrollLeft<v){1==f&&n++;getConsolePtr()("scrollLeft:"+c.scrollLeft);setTimeout(function(){hideStubbornElements(m,!0);hideObtrusiveElements(c,!0);y.createLinksSnapshot();setTimeout(function(){a.postMessage({topic:"scrollDone",x:c.scrollLeft*p,y:c.scrollTop*w})},l)},0);return}g==cModeSelected&&(R=c.scrollLeft)}if(F&&g!=cModeVisible&&g!=cModeBrowser&&(I=Math.max(0,A-40),r=c.scrollTop,c.scrollTop+=Math.max(0,I),F=r!=c.scrollTop&&c.scrollTop<x,g==cModeSelected&&((F&=c.scrollTop<t.bottom)||(S=r)),
F)){f++;c.scrollLeft=g==cModeEntire?0:G;getConsolePtr()("scrollTop:"+c.scrollTop);K=!0;setTimeout(function(){J&&Q.undoSwitchingToFixedPositions();hideStubbornElements(m);hideObtrusiveElements(c,!1);y.createLinksSnapshot();setTimeout(function(){a.postMessage({topic:"scrollDone",x:c.scrollLeft*p,y:c.scrollTop*w})},l)},l);return}b={topic:"scrollFinished",div:0,left:0,top:0,width:g==cModeEntire?v:z,height:g==cModeEntire?x:A,ratioW:p,ratioH:w,rows:f,cols:n,cw:z,ch:A,hScrollbar:window.innerHeight>A,vScrollBar:window.innerWidth>
z,cropLeft:0,cropRight:0,cropTop:0,cropBottom:0};q&&frameElement?(b.div=1,b.left=frameElement.clientLeft+frameElement.offsetLeft,b.top=frameElement.clientTop+frameElement.offsetTop):m&&(r=m.getClientRects(),b.div=1,0<r.length&&(b.left=m.clientLeft+r[0].left,b.top=m.clientTop+r[0].top),m.style.zIndex=N,enableFloatingInView());g===cModeSelected&&(b.width=R-G+z,b.height=S-L+A,b.crop=!0,b.cropLeft=t.left-G,b.cropTop=t.top-L,b.cropRight=b.cropLeft+(t.right-t.left),b.cropBottom=b.cropTop+(t.bottom-t.top));
getConsolePtr()(JSON.stringify(b));r=getOffsets(b,g,t);y.getLinks(b,r);y.clearAttributes();y=void 0;b.left*=p;b.top*=w;b.width*=p;b.height*=w;b.cw*=p;b.ch*=w;b.cropLeft*=p;b.cropTop*=w;b.cropRight*=p;b.cropBottom*=w;c.scrollLeft=P;c.scrollTop=O;document.documentElement.style.scrollBehavior=W;T&&(c.style.overflow=U,c.style.height=V);void 0!==B&&(document.body.style.overflowX=B);void 0!==D&&(document.documentElement.style.overflowY=D);void 0!==E&&(document.documentElement.style.overflowX=E);enableScrollEvent();
g!=cModeVisible&&g!=cModeBrowser&&enableSomeElements(!0);showHiddenElements();removeCustomAttributes();setTimeout(function(){a.postMessage(b)},l);break;case "sendFireShotCaptureCompleteEvent":window.fsPendingCB&&(r={cbId:window.fsPendingCB,data:b.data},"undefined"!==typeof cloneInto&&(r=cloneInto(r,document.defaultView)),r=new document.defaultView.CustomEvent("FireShotCaptureCompleteEvent",{detail:r}),document.dispatchEvent(r))}getConsolePtr()("CS:"+b.topic)})}});
