/*
 FireShot - Webpage Screenshots and Annotations
 Copyright (C) 2007-2019 Evgeny Suslikov (evgeny@suslikov.ru)
*/
var cActionEdit=0,cActionSave=1,cActionClipboard=2,cActionEMail=3,cActionPaint=4,cActionUpload=5,cActionPrint=7,cActionBASE64Content=8,cActionSavePDF=10,cActionSendOneNote=11,cActionMultiPDF=12,cActionSilentAdd=13,cActionUpgrade=100,cActionSilentSave=101,cModeVisible=0,cModeEntire=1,cModeSelected=2,cModeBrowser=3,cModeTabs=4,cLastActionPref="lastAction",cLastModePref="lastMode",cShortcutPref="hotkey",cShortcutPrefVisible="hotkeyVisible",cShortcutPrefSelection="hotkeySelection",cShortcutPrefEntire=
"hotkeyEntire",cShortcutPrefBrowser="hotkeyBrowser",cShortcutPrefTabs="hotkeyTabs",cAPISupport="enableAPI",cDebugPref="fsDebug",cShortcutPrefVisibleAction="hotkeyVisibleAction",cShortcutPrefSelectionAction="hotkeySelectionAction",cShortcutPrefEntireAction="hotkeyEntireAction",cShortcutPrefBrowserAction="hotkeyBrowserAction",cShortcutPrefTabsAction="hotkeyTabsAction",cPluginProModePref="pluginProMode",cRegisteredPref="registeredMode",cFirstTimeRun="firstTimeRunFlag",cCurrentVersion="curVersion",cTemplatePref=
"filenameTemplate",cTemplateNumberPref="filenameNumber",cTemplateNumberPadCheckPref="filenameNumberPadCheck",cTemplateNumberPadValuePref="filenameNumberPadValue",cContextMenuIntegrationPref="contextMenuIntegration",cDefaultFolderPref="defaultFolderLite",cDefaultFolderValue="FireShot",cOpenFolderAterSavingPref="openFolderAfterSavingLite",cNoFilenamePromptPref="noFilenamePrompt",cCloseTabAfterSaving="closeTabAfterSavingLite",cUpdCheckIgnorePeriodPref="uCheck",cUpdEmitPref="uEmit",cUpdInfoURL="https://ssl.getfireshot.com/images/api/utm.gif?dummy=",
cOnlyLitePref="onlyLite",cForceNativeInstallEnabled="nativeInstall",cLikedPref="userLikedFireShot",cRatedPref="userRatedFireShot",cResultPageShownCntrPref="resultPageShown",cUpdGracePeriod=1296E6,cUpdMaxPeriod=2592E5,cUpdTimeCheckInterval=432E5,cUpdCheckDelay=6E5,cTemplateFilenameMaxLen="filenameMaxLen",cDefaultImageFormatPref="png",cQueuedBadgeURLPref="queuedBadgeURL",cShowSelectionHintPref="showSelectionHint.1",cAdvancedFeaturesAvailPref="advancedFeaturesAvailable",cAdvancedFeaturesCheckURL="https://ssl.getfireshot.com/images/api/chromefeatures.gif?dummy=",
cDefaultShortcut=getOSFriendlyShortcut("Ctrl+Alt+Shift+Z"),cDefaultShortcutVisible=getOSFriendlyShortcut("Ctrl+Alt+Shift+X"),cDefaultShortcutSelection=getOSFriendlyShortcut("Ctrl+Alt+Shift+C"),cDefaultShortcutEntire=getOSFriendlyShortcut("Ctrl+Alt+Shift+V"),cDefaultShortcutBrowser=getOSFriendlyShortcut("Ctrl+Alt+Shift+B"),cDefaultShortcutTabs=getOSFriendlyShortcut("Ctrl+Alt+Shift+T"),cDefaultShortcutVisibleAction=0,cDefaultShortcutSelectionAction=0,cDefaultShortcutEntireAction=0,cDefaultShortcutBrowserAction=
0,cDefaultShortcutTabsAction=0,cDefaultTemplate="FireShot Capture %n - %t - %e",cNativeInstallerURLTemplate="https://getfireshot.com/downloads/%VERSION%/fireshot-chrome-plugin.exe",extensionId=chrome.runtime.id,isDebug="true"===localStorage[cDebugPref]||"legfpnnmhhnhjgekmmbkilmijnjoehne"==extensionId,isOldChromeVesion=!1;(function(){var a=console.log;try{a("")}catch(b){isOldChromeVesion=!0}})();getConsolePtr()("Extension ID: "+extensionId);isOnlyLite()&&getConsolePtr()("Forcing Lite mode.");
function isOnlyLite(){return"true"==localStorage[cOnlyLitePref]||"1"==localStorage[cOnlyLitePref]}function isNativeSupported(){return isOnlyLite()?!1:fsNativePlugin.ready}function getPlugin(){return isNativeSupported()?fsNativePlugin:getJSPlugin()}
function pluginCommand(a,b){try{b=b?b:{};var c=getPlugin();b.JSONCommand=a;if(isDebug)if(b.dataurl){var e=b.dataurl;b.dataurl="<cut>";getConsolePtr()("plugin command: "+a+" : "+JSON.stringify(b));b.dataurl=e}else getConsolePtr()("plugin command: "+a+" : "+JSON.stringify(b));return isNativeSupported()?c.launchJSON(b):c.launchFunction(a,b)}catch(d){return logError(d.message),!1}}function openURL(a){chrome.tabs.create({url:a})}function getOption(a,b){a=localStorage[a];return void 0===a?b:a}
function getConsolePtr(){return!isOldChromeVesion&&isDebug?console.log:function(){}}function logToConsole(a){if(isDebug){var b=new Date;console.log(b.getHours()+":"+b.getMinutes()+":"+b.getSeconds()+"."+b.getMilliseconds()+"   "+a)}}function logError(a){console.error("FireShot: "+a)}
function getSBHeight(a){if(a.scrollbars.visible){var b=a.document.createElement("div");b.setAttribute("style","position: fixed; margin: 0px; padding: 0px; border: none; visibility: hidden;  top: 0px; left: 0px; width: 1px; height: 100%; z-index: -1;");a.document.body.appendChild(b);var c=a.innerHeight-b.offsetHeight;a.document.body.removeChild(b);return 0<c&&40>c?c:0}return 0}function getExtension(){return chrome.extension.getBackgroundPage()}
function getShortcut(a){var b=[];a.ctrlKey&&b.push("control");a.altKey&&b.push("alt");a.metaKey&&b.push("meta");a.shiftKey&&b.push("shift");b=b.join("+");if(""===b||32>a.which)return"";b=getOSFriendlyShortcut(b.replace("alt","Alt").replace("shift","Shift").replace("control","Ctrl").replace("meta","Meta").replace("accel","Ctrl"))+"+";a=32==a.which?"Space":String.fromCharCode(a.which).toUpperCase();return b+a}
function getOSFriendlyShortcut(a){return isMac()?a.replace("Ctrl","Control").replace("Meta","Cmd"):a}function isWindows(){return-1!=navigator.appVersion.indexOf("Win")}function isMac(){return null!==navigator.platform.match(/^mac/i)}function isOpera(){return null!==navigator.appVersion.match(/OPR\/\d+\./i)||"pbjmgmedeliohhbaefhlplndokcbmjio"===extensionId}
function i18nPrepare(){for(var a=document.createNodeIterator(document.documentElement,NodeFilter.SHOW_ELEMENT,function(a){return null===a.getAttribute("data-i18n")?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT},!1),b;b=a.nextNode();){var c=chrome.i18n.getMessage(b.getAttribute("data-i18n"));b.innerText=""!==c?c:"#"+b.innerText}}function gaTrack(a,b,c,e){}
function getFilenameLite(){function a(a,b,c){for(a=a.toString();a.length<c;)a=b+a;return a}var b=getOption(cTemplateFilenameMaxLen,100),c=0,e=getOption(cTemplateNumberPref,1);do{var d=getOption(cTemplatePref,cDefaultTemplate);var g=new Date,f=getExtension().tabURL,h=getExtension().tabTitle,k=(new URL(f)).hostname;d=d.replace(/%n/g,"true"===getOption(cTemplateNumberPadCheckPref,"true")?a(e,0,getOption(cTemplateNumberPadValuePref,3)):e);d=d.replace(/%y/g,g.getFullYear());d=d.replace(/%m/g,a(g.getMonth()+
1,0,2));d=d.replace(/%d/g,a(g.getDate(),0,2));d=d.replace(/%H/g,a(g.getHours(),0,2));d=d.replace(/%M/g,a(g.getMinutes(),0,2));d=d.replace(/%S/g,a(g.getSeconds(),0,2));1==c?f=f.substr(0,Math.max(14,b-d.length+1)):2==c?(f=f.replace(/(.*)\?.*/gi,"$1"),d=d.replace(/%u/g,f),h=h.substr(0,Math.max(14,b-d.length+1))+"_"):3==c&&(f=f.substr(0,(b-d.length)/2-1),d=d.replace(/%u/g,f),h=h.substr(0,b-d.length-1)+"_");d=d.replace(/%u/g,f);d=d.replace(/%t/g,h);d=d.replace(/%e/g,k);d=d.replace(/[:\/\\\*\?<>\|"]/g,
function(a){switch(a){case "<":return"{";case ">":return"}";case "|":return"-"}return"_"})}while(4>++c&&d.length>b);""===d&&(d="Untitled");localStorage[cTemplateNumberPref]=parseInt(e)+1;return d}function showBadge(a){localStorage[cQueuedBadgeURLPref]=a;chrome.browserAction.setBadgeText({text:a&&"undefined"!=a?"New":""});a&&getConsolePtr()("Setting badge for url: "+a)}function getLastAction(){return parseInt(getOption(cLastActionPref,cActionEdit))}
function getLastMode(){return parseInt(getOption(cLastModePref,cModeEntire))}function setLastActionAndMode(a,b){localStorage[cLastActionPref]=a;localStorage[cLastModePref]=b}function isProMode(){return"true"==localStorage[cPluginProModePref]}function getIntersection(a,b,c,e,d,g,f,h){return!(a+c<=d||d+f<=a||b+e<=g||g+h<=b)}function rectsIntersected(a,b){return a.left<b.left+b.width&&b.left<a.left+a.width&&a.top<b.top+b.height&&b.top<a.top+a.height}
function isChildOf(a,b){for(b=b.parentNode;b;){if(b==a)return!0;b=b.parentNode}return!1}
function difference(a,b){var c=[];if(!rectsIntersected(a,b))return[a];var e=a.top,d=a.height,g=a.left+a.width,f=a.top+a.height,h=b.left+b.width,k=b.top+b.height;b.top>a.top&&(c.push({left:a.left,top:a.top,width:a.width,height:b.top-a.top}),e=b.top,d-=b.top-a.top);k<f&&(c.push({left:a.left,top:k,width:a.width,height:f-k}),d=k-e);b.left>a.left&&c.push({left:a.left,top:e,width:b.left-a.left,height:d});h<g&&c.push({left:h,top:e,width:g-h,height:d});return c}
function isScrollableStyle(a){return a&&("scroll"==a.getPropertyValue("overflow")||"auto"==a.getPropertyValue("overflow")||"scroll"==a.getPropertyValue("overflow-y")||"auto"==a.getPropertyValue("overflow-y")||"scroll"==a.getPropertyValue("overflow-x")||"auto"==a.getPropertyValue("overflow-x"))&&"none"!=a.getPropertyValue("display")&&"hidden"!=a.getPropertyValue("visibility")}
function isOverflowed(a){return a&&"none"!==a.getPropertyValue("display")&&("hidden"===a.getPropertyValue("overflow")||"hidden"===a.getPropertyValue("overflow-y")||"auto"===a.getPropertyValue("overflow-y")||"scroll"==a.getPropertyValue("overflow-y")||"hidden"===a.getPropertyValue("overflow-x")||"auto"===a.getPropertyValue("overflow-x")||"scroll"==a.getPropertyValue("overflow-x"))}function getAdvancedFeaturesAvailable(){return!0}
function checkAdvancedFeatures(){advFeaturesChecked||(advFeaturesChecked=!0,getFeaturesFromSite())}function getFeaturesFromSite(){}
function checkAdvancedUpdates(){function a(){var c=new Image,d=new Date,e=Math.round(d.getTime()/864E5);c.onload=function(){localStorage[cUpdEmitPref]=d.getTime()+Math.round(Math.random()*cUpdMaxPeriod);getConsolePtr()("Update info available in "+(parseInt(localStorage[cUpdEmitPref])-d.getTime())/1E3+" seconds");b()};c.onerror=function(){setTimeout(a,cUpdTimeCheckInterval)};c.src=cUpdInfoURL+e;getConsolePtr()("Checking "+c.src)}function b(){var a=parseInt(getOption(cUpdEmitPref,"0")),c=a-(new Date).getTime();
a&&0>=c?(localStorage[cUpdCheckIgnorePeriodPref]="",localStorage[cUpdEmitPref]="",getConsolePtr()("Update!"),isProMode()||showBadge("https://getfireshot.com/updated.php?app="+(isOpera()?"op":"ch")+"&src=ext&ver="+localStorage[cCurrentVersion]),checkAdvancedUpdates()):setTimeout(b,c+1E3)}if(isWindows()){getConsolePtr()("checkAdvancedUpdates");var c=parseInt(getOption(cUpdCheckIgnorePeriodPref,"0")),e=parseInt(getOption(cUpdEmitPref,"0")),d=(new Date).getTime();e?b():c?d>=c?setTimeout(a,Math.random()*
cUpdCheckDelay):setTimeout(arguments.callee,c-d+1E3):(localStorage[cUpdCheckIgnorePeriodPref]=d+cUpdGracePeriod,setTimeout(arguments.callee,cUpdGracePeriod+1E3))}}
function getJpegExtents(a){"data:image/jpeg;base64,"===a.substring(0,23)&&(a=atob(a.replace("data:image/jpeg;base64,","")));if(255!==a.charCodeAt(0)||216!==a.charCodeAt(1)||255!==a.charCodeAt(2)||224!==a.charCodeAt(3)||74!==a.charCodeAt(6)||70!==a.charCodeAt(7)||73!==a.charCodeAt(8)||70!==a.charCodeAt(9)||0!==a.charCodeAt(10))throw Error("getJpegSize requires a binary jpeg file");var b=256*a.charCodeAt(4)+a.charCodeAt(5);for(var c=4,e=a.length;c<e;){c+=b;if(255!==a.charCodeAt(c))throw Error("getJpegSize could not find the size of the image");
if(192===a.charCodeAt(c+1))return b=256*a.charCodeAt(c+5)+a.charCodeAt(c+6),a=256*a.charCodeAt(c+7)+a.charCodeAt(c+8),[a,b];c+=2;b=256*a.charCodeAt(c)+a.charCodeAt(c+1)}}function getLAShortcut(a){chrome.commands.getAll(function(b){b.forEach(function(b){"last-used-action"===b.name&&a(b.shortcut)})})}function isConsoleOpened(){var a=new Image,b=!1;Object.defineProperty(a,"id",{get:function(){b=!0}});console.log("%cFireShot console check.",a);return b}
function closestToInt(a){.009>Math.abs(a-Math.floor(a))&&(a=Math.floor(a));return a}function isAPIEnabled(){return"true"===getOption(cAPISupport,"false")}function enableAPI(a){localStorage[cAPISupport]=a}function tabsPermissionRequired(a){addTabsPermission(a,function(){getExtension().openPermissionsPage()})}
function addTabsPermission(a,b){chrome.permissions.contains({permissions:["tabs"],origins:["<all_urls>"]},function(c){c?a():chrome.permissions.request({permissions:["tabs"],origins:["<all_urls>"]},function(c){c?a():(console.log("permissions not granted"),b&&b())})})}
function addDownloadsPermission(a,b){chrome.permissions.contains({permissions:["downloads"]},function(c){c?a():chrome.permissions.request({permissions:["downloads"]},function(c){c?a():(console.log("permissions not granted"),b&&b())})})}function addGmailPermission(a,b){chrome.permissions.request({origins:["https://mail.google.com/*"]},function(c){c?a():b()})}
function initAPI(a){function b(){chrome.tabs.executeScript(null,{file:"scripts/fsAPIEvents.js",runAt:"document_start",allFrames:!0},function(){""!==chrome.runtime.lastError&&(chrome.runtime.lastError="")})}"tabSwitch"===a?chrome.permissions.request({permissions:["activeTab"],origins:["<all_urls>"]},function(a){""!==chrome.runtime.lastError&&(chrome.runtime.lastError="");a?b():getConsolePtr()("permissions not granted")}):b()}
function getNativeInstallerURL(){return cNativeInstallerURLTemplate.replace("%VERSION%",extVersion)}function isCustomBuild(){return"hpbicldbpgipcloiojdbchegbbjiobbm"==extensionId||"adpnodbfhlagloahhdhjggicnfcpggkm"==extensionId}function switchToLiteMode(){gaTrack("UA-1025658-9","fireshot.com","SwitchBackToLite");setLastActionAndMode(cActionSave,cModeEntire);fsNativePlugin.forceDisconnect();updateContextMenu()}
function fixObjectForOldChrome(a){isOldChromeVesion&&a.hasOwnProperty("frameId")&&delete a.frameId;return a};
